# Copyright 2020 Benjamin 'Benno' Falkner
#
# Permission is hereby granted, free of charge, to any person obtaining a copy 
# of this software and associated documentation files (the "Software"), to 
# deal in the Software without restriction, including without limitation the 
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or 
# sell copies of the Software, and to permit persons to whom the Software is 
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in 
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR 
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, 
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE 
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER 
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING 
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
# IN THE SOFTWARE.

new: install_deps $(n)/views.py $(n)/models.py $(n)/admin.py $(n)/serializers.py $(n)/urls.py
	echo "/^]\ni\n\tpath('$(path)',include('$(n).urls')),\n.\nwq\n" | ed $(shell basename $(CURDIR))/urls.py &> /dev/null
	echo "/^from django.urls.\nc\nfrom django.urls import path, include\n.\nwq\n" | ed $(shell basename $(CURDIR))/urls.py &> /dev/null


install_deps:
	pipenv install djangorestframework

.PHONY: $(n)/views.py $(n)/models.py
$(n)/models.py:
	@echo "# autogenerated by django.mk" > $@
	@echo "from django.db import models\n" >> $@
	@echo "class Example(models.Model):" >> $@
	@echo "\tpass" >> $@

$(n)/views.py:
	@echo "# autogenerated by django.mk" > $@
	@echo "from rest_framework import generics" >> $@
	@echo "from .models import Example" >> $@
	@echo "from .serializers import ExampleSerializer\n" >> $@
	@echo "class ExampleView(generics.ListAPIView):" >> $@
	@echo "\tqueryset = Example.objects.all()" >> $@
	@echo "\tserializer_class = ExampleSerializer" >> $@

$(n)/admin.py:
	@echo "# autogenerated by django.mk" > $@
	@echo "from django.contrib import admin" >> $@
	@echo "from .models import Example" >> $@

$(n)/serializers.py:
	@echo "# autogenerated by django.mk" > $@
	@echo "from rest_framework import serializers" >> $@
	@echo "from .models import Example\n" >> $@
	@echo "class ExampleSerializer(serializers.ModelSerializer):" >> $@
	@echo "\tclass Meta:" >> $@
	@echo "\t\tmodel = Example" >> $@
	@echo "\t\tfields = Example._meta.get_fields()" >> $@

$(n)/urls.py:
	@echo "# autogenerated by django.mk" > $@
	@echo "from django.urls import path, include" >> $@
	@echo "from . import views\n" >> $@
	@echo "urlpatterns = [" >> $@
	@echo "    path('$(n)/', views.ExampleView.as_view(),name='all')" >> $@
	@echo "]" >> $@
