# Copyright 2020 Benjamin 'Benno' Falkner
#
# Permission is hereby granted, free of charge, to any person obtaining a copy 
# of this software and associated documentation files (the "Software"), to 
# deal in the Software without restriction, including without limitation the 
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or 
# sell copies of the Software, and to permit persons to whom the Software is 
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in 
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR 
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, 
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE 
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER 
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING 
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
# IN THE SOFTWARE.


new: $(n)/views.py $(n)/urls.py $(n)/templates/$(n)/index.html $(n)/static/$(n)/style.css

$(n)/static/$(n)/style.css:
	mkdir -p $(n)/static/$(n)
	@echo "@charset \"utf-8\";" > $@

$(n)/templates/$(n)/index.html:
	mkdir -p $(n)/templates/$(n)
	@echo "<!doctype html>" > $@
	@echo "<html>" >> $@
	@echo "  <head>" >> $@
	@echo "    <meta charset=\"utf-8\">" >> $@
	@echo "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">" >> $@
	@echo "    <link rel=\"stylesheet\" href=\"{% static \"$(n)/style.css\" %}\">" >> $@
	@echo "    <title>$(n)</title>" >> $@
	@echo "  </head>" >> $@
	@echo "  <body>" >> $@
	@echo "    <h1>$(n)</h1>" >> $@
	@echo "    <p>This is a placeholder</p>" >> $@
	@echo "  </body>" >> $@
	@echo "</html>" >> $@

$(n)/views.py: 
	@echo "# autogenerated by django.mk\n" > $@
	@echo "from django.shortcuts import render\n" >> $@
	@echo "def index(request):\n" >> $@
	@echo "\treturn render(request, 'frontend/index.html')" >> $@

$(n)/urls.py:
	@echo "# autogenerated by django.mk\n" > $@
	@echo "from django.urls import path, include" >> $@
	@echo "from . import views\n" >> $@
	@echo "urlpatterns = ["  >> $@
	@echo "\tpath('', views.index)" >> $@
	@echo "]" >> $@
